### PR TITLE
Add Polish to subtitles

### PR DESCRIPTION
**Pull request by xdk78**

### CODE REVIEW

**Comment by Kylart** [comment]
But KawAnime does not have any way of getting polish subtitles at the moment :<

**Comment by xdk78** [comment]
#21 and some torrents have polish subtitles included

**Comment by Kylart** [comment]
#21 isn't the issue this list is about yet and the torrents of the "supported" fansubs don't have polish subtitles.

**Comment by xdk78** [comment]
Ok, sorry it was my misunderstood

**Comment by Kylart** [comment]
Don't worry tho, I haven't forgotten polish people, I'm actually thinking a lot about the subtitles-related issues like #21.

**Pull request closed without merging**
